version: '2.2'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms4g -Xmx4g
      - xpack.monitoring.collection.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elkdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601

  logstash:
    image: docker.elastic.co/logstash/logstash:7.0.0
    container_name: logstash
    environment:
      - xpack.monitoring.elasticsearch.url=http://elasticsearch:9200
      - xpack.monitoring.enabled=true
    volumes:
      - ./logs/data.csv:/data.csv
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf

volumes:
  elkdata:
    driver: local
